# Generated by Django 4.1.1 on 2022-10-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceProvider', '0001_initial'),
        ('custumer', '0002_remove_customer_id_customer_photo_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_info',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custumer.customer')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
                ('sp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.serviceprovider')),
            ],
        ),
    ]
