# Generated by Django 4.1.1 on 2022-10-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(default='', upload_to=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
