# Generated by Django 4.1.1 on 2022-10-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAssign',
            fields=[
                ('sa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_info.booking_info')),
            ],
        ),
    ]
