# Generated by Django 4.1.1 on 2022-10-25 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('sp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='')),
                ('photo', models.ImageField(default='', upload_to='')),
                ('p_num', models.IntegerField()),
                ('nid', models.IntegerField()),
                ('sp_rating', models.FloatField(max_length=4)),
                ('ex', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
